spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/sobro?characterEncoding=utf8
    username: sobro
    password: sobro!21
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

primary:
  datasource:
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/sobro?characterEncoding=utf8
    username: sobro
    password: sobro!21
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    minimum-idle: 5
    maximum-pool-size: 20
    connection-timeout: 30000
    connection-init-sql: SELECT 1
    validation-timeout: 250
---
logging:
  config: classpath:log4j2.yml

hcd:
    svcCode: 6uQI85sVOdmRSVBS0TiM
    svcUrl: https://vtalksvc.dev.work.uplus.co.kr
    apiUrl: https://api.dev.ulsp.uplus.co.kr
    tokenUrl: /sobro-dev-login/auth
    roomCreate: /sobro-dev-room/create
    roomUpdate: /sobro-dev-room/update
    roomDelete: /sobro-dev-room/delete
    roomTokenUrl: /sobro-dev-login/roomTokenCreate
    fileListUrl: /sobro-dev-file/list
    fileUploadUrl: /sobro-dev-file/upload
    fileDeleteUrl: /sobro-dev-file/delete
    fileDownload: /sobro-dev-file/download
    
#hcd:
    #svcCode: 6uQI85sVOdmRSVBS0TiM
    ##svcUrl: https://210.220.167.91:8080
    #svcUrl: https://vtalksvc.dev.work.uplus.co.kr
    #apiUrl: https://api.ulsp.uplus.co.kr
    #tokenUrl: /sobro-login/auth
    #roomCreate: /sobro-room/create
    #roomUpdate: /sobro-room/update
    #roomDelete: /sobro-room/delete
    #roomTokenUrl: /sobro-login/roomTokenCreate
    #fileListUrl: /sobro-files/list
    #fileUploadUrl: /sobro-files/upload
    #fileDeleteUrl: /sobro-files/delete
    #fileDownload: /sobro-files/download
    
--- #local
spring:
  profiles: local
server:
  port: 8081
  max-http-header-size: 400000
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
    max-connections: 500
    connection-timeout: 60
    accept-count: 2000
    threads:
      min-spare: 100
      max: 500
#    basedir: /
#    accesslog:
#      enabled: true
#      directory: /logs/pltfapi/accesslog/
#      file-date-format: yyyy-MM-dd-HH
#      pattern: "%h %l %u %t %r %s %b %{Referer}i %{User-Agent}i %D %{Cookie}i %p %a %{remote}p %{X-Forwarded-For}i"
  #ssl:
    #enabled: true
    #key-store: keystore.p12
    #key-store-password: 123456
    #key-store-type: PKCS12
    #key-alias: bns-ssl

# tmp파일 경로
temp:
  path: D:/tmp/fileUpload
--- #dev
spring:
  profiles: dev
server:
  port: 8080
  max-http-header-size: 40000
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
    max-connections: 500
    connection-timeout: 60
    accept-count: 2000
    threads:
      min-spare: 100
      max: 500
#    basedir: /
#    accesslog:
#      enabled: true
#      directory: /logs/pltfapi/accesslog/
#      file-date-format: yyyy-MM-dd-HH
#      pattern: "%h %l %u %t %r %s %b %{Referer}i %{User-Agent}i %D %{Cookie}i %p %a %{remote}p %{X-Forwarded-For}i"

# tmp파일 경로
temp:
  path: /home/apaadm/tmp/fileUpload